repos:
  - repo: meta
    hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: end-of-file-fixer
      # See <https://docs.python.org/3/library/re.html#re.X>
      exclude: |
        (?x)^(
            docs/(
                numerary-encumbered\.svg|
                perf_.*\.txt
            )
        )$
    - id: mixed-line-ending
    - id: trailing-whitespace
      # See <https://docs.python.org/3/library/re.html#re.X>
      exclude: |
        (?x)^(
            docs/(
                numerary-encumbered\.svg|
                perf_.*\.txt
            )
        )$
    - id: check-added-large-files
    - id: check-case-conflict
    # - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: destroyed-symlinks
    - id: detect-private-key
    # - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
